/**
 * FILE CARD COMPONENT
 *
 * Displays a file in the file manager grid with preview support.
 * Renders actual images/videos for visual files, icons for others.
 *
 * FEATURES:
 * - Actual image rendering for visual files
 * - Video preview with play button overlay (requires thumbnail)
 * - File type icons for non-visual files
 * - Visibility badge (public/private) for user awareness
 * - Context menu for file actions (including Copy Link)
 * - Selection state
 *
 * SECURITY MODEL:
 * - PUBLIC files: Direct CDN URL - anyone with the link can access
 * - PRIVATE files: Authenticated API route - only signed-in org members can access
 *
 * COPY LINK BEHAVIOR:
 * - PUBLIC: Copies direct CDN URL (embeddable, shareable externally)
 * - PRIVATE: Copies API route URL (recipients must be signed in to org)
 *
 * The `accessUrl` prop is used for displaying files in the dashboard:
 * - PUBLIC: Direct CDN URL (fast, cacheable)
 * - PRIVATE: `/api/storage/[fileId]` which checks authentication + org membership
 */

'use client'

import { useState, useCallback, useRef, useEffect } from 'react'
import { cn } from '@/lib/utils'
import { MoreHorizontal, Lock, Globe, Download, Trash2, Pencil, Move, Play, Link2, X, Check } from 'lucide-react'
import { toast } from 'sonner'
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuSeparator,
  DropdownMenuTrigger,
} from '@/components/ui/dropdown-menu'
import { Button } from '@/components/ui/button'
import { Badge } from '@/components/ui/badge'
import { FileIcon } from './file-icons'
import { VideoPlayer } from './video-player'
import type { FileCategory, FileVisibility, VideoProcessingStatus } from '@/generated/prisma'
import Image from 'next/image'

// ============================================================================
// TYPES
// ============================================================================

interface FileCardProps {
  /** File ID */
  id: string
  /** Organization ID (required for video playback) */
  organizationId?: string
  /** Original filename */
  name: string
  /** File extension (e.g., "pdf", "mp4") */
  extension: string
  /** File category for icon fallback */
  category: FileCategory
  /** File size in bytes */
  size: number
  /** Thumbnail URL for images/videos */
  thumbnailUrl?: string | null
  /**
   * Access URL for viewing/displaying the file
   * - PUBLIC files: Direct CDN URL
   * - PRIVATE files: Authenticated API route (/api/storage/[fileId])
   */
  accessUrl?: string | null
  /**
   * Public CDN URL (only available for PUBLIC files)
   * Used for Copy Link feature - ONLY works for public files
   */
  publicUrl?: string | null
  /** File visibility */
  visibility: FileVisibility

  // ========================
  // Video HLS Fields
  // ========================
  /** HLS manifest URL for PUBLIC videos (CDN URL) */
  hlsManifestUrl?: string | null
  /** Poster/thumbnail URL for videos (generated by HLS processing) */
  posterUrl?: string | null
  /** Video processing status */
  videoProcessingStatus?: VideoProcessingStatus | null

  /** Whether the file is selected */
  isSelected?: boolean
  /** Click handler */
  onClick?: () => void
  /** Double-click handler (preview/download) */
  onDoubleClick?: () => void
  /**
   * Rename handler - receives new name
   * Called when user finishes inline editing
   */
  onRename?: (newName: string) => void
  /** Whether rename is in progress (for loading state) */
  isRenaming?: boolean
  /** Delete handler */
  onDelete?: () => void
  /** Move handler */
  onMove?: () => void
  /** Download handler */
  onDownload?: () => void
  /** Toggle visibility handler */
  onToggleVisibility?: () => void
  /** Additional className */
  className?: string
}

// ============================================================================
// UTILITY FUNCTIONS
// ============================================================================

/**
 * Copy text to clipboard
 * Uses modern Clipboard API which requires user gesture context
 * @param text - The text to copy
 * @param successMessage - Custom success message to show
 */
function copyToClipboard(text: string, successMessage: string = 'Link copied to clipboard'): void {
  // The Clipboard API needs to be called synchronously within user gesture
  // Using setTimeout to ensure dropdown doesn't interfere
  setTimeout(() => {
    // Create a temporary input that's visible (required for some browsers)
    const input = document.createElement('input')
    input.setAttribute('value', text)
    input.style.position = 'fixed'
    input.style.left = '0'
    input.style.top = '0'
    input.style.opacity = '0'
    input.style.pointerEvents = 'none'
    document.body.appendChild(input)
    input.select()
    input.setSelectionRange(0, text.length) // For mobile

    try {
      const successful = document.execCommand('copy')
      if (successful) {
        toast.success(successMessage)
      } else {
        // Try Clipboard API as backup
        navigator.clipboard?.writeText(text)
          .then(() => toast.success(successMessage))
          .catch(() => toast.error('Failed to copy link'))
      }
    } catch {
      toast.error('Failed to copy link')
    }

    document.body.removeChild(input)
  }, 100)
}

/**
 * Formats file size to human-readable string
 * e.g., 1024 -> "1 KB", 1048576 -> "1 MB"
 */
function formatFileSize(bytes: number): string {
  if (bytes === 0) return '0 B'

  const units = ['B', 'KB', 'MB', 'GB', 'TB']
  const k = 1024
  const i = Math.floor(Math.log(bytes) / Math.log(k))

  return `${parseFloat((bytes / Math.pow(k, i)).toFixed(1))} ${units[i]}`
}

/**
 * Check if file category can have a visual preview
 */
function isVisualFile(category: FileCategory): boolean {
  return category === 'IMAGE' || category === 'VIDEO'
}

// ============================================================================
// PREVIEW COMPONENTS
// ============================================================================

/**
 * Image Preview Component
 *
 * Renders actual image preview for both PUBLIC and PRIVATE files:
 * - PUBLIC files: Uses next/image with direct CDN URL (fast, cacheable)
 * - PRIVATE files: Uses regular <img> tag with accessUrl (/api/storage/[fileId])
 *   which redirects to a presigned R2 URL. next/image can't follow redirects,
 *   but a regular <img> tag handles them natively. Same pattern as VideoPreview
 *   for private video posters.
 */
function ImagePreview({
  accessUrl,
  thumbnailUrl,
  name,
  isPrivate,
}: {
  accessUrl?: string | null
  thumbnailUrl?: string | null
  name: string
  isPrivate?: boolean
}) {
  const imageUrl = accessUrl || thumbnailUrl

  // No URL available — show placeholder
  if (!imageUrl) {
    return (
      <div className="flex flex-col items-center justify-center gap-2 text-muted-foreground h-full">
        {isPrivate ? (
          <>
            <Lock className="w-8 h-8 opacity-50" />
            <span className="text-xs">Private</span>
          </>
        ) : (
          <>
            <Globe className="w-8 h-8 opacity-50" />
            <span className="text-xs">No Preview</span>
          </>
        )}
      </div>
    )
  }

  /**
   * Private files: Use regular <img> tag because the accessUrl is an API route
   * (/api/storage/[fileId]) that returns a 302 redirect to a presigned R2 URL.
   * next/image can't handle redirects, but <img> follows them natively.
   */
  if (isPrivate) {
    return (
      <img
        src={imageUrl}
        alt={name}
        className="absolute inset-0 w-full h-full object-cover"
      />
    )
  }

  // Public files: Use next/image for optimized loading via CDN
  return (
    <Image
      src={imageUrl}
      alt={name}
      fill
      className="object-cover"
      sizes="(max-width: 640px) 50vw, (max-width: 1024px) 25vw, 16vw"
    />
  )
}

/**
 * Video Preview Component with Inline Playback
 *
 * Shows thumbnail with play button overlay for videos.
 * When play button is clicked, shows inline video player.
 * Supports both PUBLIC (CDN URL) and PRIVATE (API route) videos.
 *
 * PUBLIC videos: Use hlsManifestUrl (CDN) directly
 * PRIVATE videos: Use fileId + organizationId (API route with auth)
 */
function VideoPreview({
  fileId,
  organizationId,
  thumbnailUrl,
  posterUrl,
  hlsManifestUrl,
  visibility,
  videoProcessingStatus,
  name,
  isPlaying,
  onPlayClick,
  onCloseClick,
}: {
  fileId: string
  organizationId?: string
  thumbnailUrl?: string | null
  posterUrl?: string | null
  hlsManifestUrl?: string | null
  visibility: FileVisibility
  videoProcessingStatus?: VideoProcessingStatus | null
  name: string
  isPlaying: boolean
  onPlayClick: () => void
  onCloseClick: () => void
}) {
  // Determine if video is ready to play (processing complete)
  const isVideoReady = videoProcessingStatus === 'COMPLETED'

  // Construct poster URL based on visibility
  // For PRIVATE videos, poster might need to go through API route
  // For PUBLIC videos, use the CDN URL directly
  const getEffectivePosterUrl = (): { url: string; isApiRoute: boolean } | null => {
    // If we have a direct poster URL (PUBLIC videos), use it
    if (posterUrl) return { url: posterUrl, isApiRoute: false }
    // If we have a thumbnail, use it
    if (thumbnailUrl) return { url: thumbnailUrl, isApiRoute: false }
    // For completed videos, construct poster URL via API route
    // This handles PRIVATE videos where posterUrl is null but posterKey exists
    if (isVideoReady) {
      return { url: `/api/storage/hls/${fileId}/poster.jpg`, isApiRoute: true }
    }
    return null
  }

  const posterData = getEffectivePosterUrl()
  const previewImage = posterData?.url || null
  const isApiRoutePoster = posterData?.isApiRoute || false
  const hasPreview = !!previewImage

  // If video is playing, show the video player
  if (isPlaying && isVideoReady) {
    return (
      <div className="absolute inset-0 bg-black z-20">
        {/* Close button to return to thumbnail */}
        <Button
          variant="ghost"
          size="icon"
          className="absolute top-2 right-2 z-30 h-7 w-7 bg-black/70 hover:bg-black/90 text-white"
          onClick={(e) => {
            e.stopPropagation()
            onCloseClick()
          }}
        >
          <X className="w-4 h-4" />
        </Button>

        {/* Inline Video Player - fill the card container */}
        {visibility === 'PUBLIC' && hlsManifestUrl ? (
          // PUBLIC: Use CDN URL directly
          <VideoPlayer
            src={hlsManifestUrl}
            poster={posterUrl || thumbnailUrl || undefined}
            autoPlay
            muted
            controls
            className="!aspect-auto absolute inset-0 !rounded-none"
          />
        ) : (
          // PRIVATE: Use fileId + organizationId (authenticated API route)
          <VideoPlayer
            fileId={fileId}
            organizationId={organizationId}
            autoPlay
            muted
            controls
            className="!aspect-auto absolute inset-0 !rounded-none"
          />
        )}
      </div>
    )
  }

  // Show thumbnail with play button overlay
  return (
    <div className="relative w-full h-full">
      {hasPreview ? (
        <>
          {/* Video thumbnail/poster */}
          {/* Use regular img for API routes (Next.js Image doesn't handle them well) */}
          {isApiRoutePoster ? (
            <img
              src={previewImage!}
              alt={name}
              className="absolute inset-0 w-full h-full object-cover"
            />
          ) : (
            <Image
              src={previewImage!}
              alt={name}
              fill
              className="object-cover"
              sizes="(max-width: 640px) 50vw, (max-width: 1024px) 25vw, 16vw"
            />
          )}
          {/* Play button overlay */}
          {isVideoReady ? (
            <div
              className="absolute inset-0 flex items-center justify-center bg-black/20 hover:bg-black/30 transition-colors cursor-pointer"
              onClick={(e) => {
                e.stopPropagation()
                onPlayClick()
              }}
            >
              <div className="w-12 h-12 rounded-full bg-black/60 hover:bg-black/80 flex items-center justify-center transition-colors">
                <Play className="w-6 h-6 text-white fill-white ml-1" />
              </div>
            </div>
          ) : (
            // Video not ready - show processing indicator
            <div className="absolute inset-0 flex items-center justify-center bg-black/40">
              <div className="text-center">
                <div className="w-10 h-10 rounded-full bg-black/60 flex items-center justify-center mx-auto mb-1">
                  <Play className="w-5 h-5 text-white/50 ml-0.5" />
                </div>
                <span className="text-[10px] text-white/80">
                  {videoProcessingStatus === 'PROCESSING' ? 'Processing...' :
                   videoProcessingStatus === 'PENDING' ? 'Queued' :
                   videoProcessingStatus === 'FAILED' ? 'Failed' : 'Not ready'}
                </span>
              </div>
            </div>
          )}
        </>
      ) : (
        // No thumbnail available - show video placeholder with play icon
        <div className="flex flex-col items-center justify-center gap-2 text-muted-foreground bg-muted/50 h-full">
          <div
            className={cn(
              "w-14 h-14 rounded-full bg-muted flex items-center justify-center",
              isVideoReady && "cursor-pointer hover:bg-muted/80 transition-colors"
            )}
            onClick={isVideoReady ? (e) => {
              e.stopPropagation()
              onPlayClick()
            } : undefined}
          >
            <Play className="w-7 h-7 ml-1" />
          </div>
          <span className="text-xs">
            {videoProcessingStatus === 'PROCESSING' ? 'Processing...' :
             videoProcessingStatus === 'PENDING' ? 'Queued' :
             videoProcessingStatus === 'FAILED' ? 'Failed' :
             isVideoReady ? 'Video' : 'Video'}
          </span>
        </div>
      )}
    </div>
  )
}

// ============================================================================
// MAIN COMPONENT
// ============================================================================

/**
 * FileCard Component
 *
 * Displays a file in the file manager with preview and actions.
 * Renders actual images for IMAGE category, inline video player for VIDEO,
 * and file type icons for everything else.
 *
 * VIDEO PLAYBACK:
 * - Click play button to start inline video playback
 * - Videos start muted (browser requirement)
 * - PUBLIC videos use CDN HLS URL
 * - PRIVATE videos use authenticated API route
 *
 * @example
 * <FileCard
 *   id="file_123"
 *   organizationId="org_456"
 *   name="course-video.mp4"
 *   extension="mp4"
 *   category="VIDEO"
 *   size={1024000}
 *   visibility="PUBLIC"
 *   hlsManifestUrl="https://cdn.../master.m3u8"
 *   posterUrl="https://cdn.../poster.jpg"
 *   videoProcessingStatus="COMPLETED"
 *   onClick={() => selectFile('file_123')}
 * />
 */
export function FileCard({
  id,
  organizationId,
  name,
  extension,
  category,
  size,
  thumbnailUrl,
  accessUrl,
  publicUrl,
  visibility,
  hlsManifestUrl,
  posterUrl,
  videoProcessingStatus,
  isSelected,
  onClick,
  onDoubleClick,
  onRename,
  isRenaming,
  onDelete,
  onMove,
  onDownload,
  onToggleVisibility,
  className,
}: FileCardProps) {
  // State for inline video playback
  const [isVideoPlaying, setIsVideoPlaying] = useState(false)

  // State for inline name editing
  const [isEditing, setIsEditing] = useState(false)
  const [editName, setEditName] = useState(name)
  const inputRef = useRef<HTMLInputElement>(null)

  const isImage = category === 'IMAGE'
  const isVideo = category === 'VIDEO'

  // Both PUBLIC and PRIVATE files can have shareable links
  // PUBLIC: Direct CDN URL (anyone can access)
  // PRIVATE: Authenticated API route (only logged-in org members can access)
  const shareableUrl = visibility === 'PUBLIC' ? publicUrl : `/api/storage/${id}`
  const canCopyLink = !!shareableUrl

  // Handlers for video playback
  const handlePlayVideo = useCallback(() => {
    setIsVideoPlaying(true)
  }, [])

  const handleCloseVideo = useCallback(() => {
    setIsVideoPlaying(false)
  }, [])

  // Focus input when entering edit mode
  useEffect(() => {
    if (isEditing && inputRef.current) {
      inputRef.current.focus()
      inputRef.current.select()
    }
  }, [isEditing])

  // Reset edit name when name prop changes (e.g., after successful rename)
  useEffect(() => {
    setEditName(name)
  }, [name])

  /**
   * Enter edit mode on double-click
   */
  const handleNameDoubleClick = useCallback((e: React.MouseEvent) => {
    e.stopPropagation()
    if (!onRename) return
    setIsEditing(true)
  }, [onRename])

  /**
   * Save the new name
   */
  const handleSaveName = useCallback(() => {
    const trimmedName = editName.trim()
    if (trimmedName && trimmedName !== name) {
      onRename?.(trimmedName)
    }
    setIsEditing(false)
  }, [editName, name, onRename])

  /**
   * Cancel editing and reset name
   */
  const handleCancelEdit = useCallback(() => {
    setEditName(name)
    setIsEditing(false)
  }, [name])

  /**
   * Handle keyboard events in edit mode
   */
  const handleKeyDown = useCallback((e: React.KeyboardEvent) => {
    if (e.key === 'Enter') {
      e.preventDefault()
      handleSaveName()
    } else if (e.key === 'Escape') {
      e.preventDefault()
      handleCancelEdit()
    }
  }, [handleSaveName, handleCancelEdit])

  return (
    <div
      className={cn(
        'group relative flex flex-col rounded-xl overflow-hidden cursor-pointer transition-all duration-200',
        'border border-border/50 bg-card',
        'hover:border-border hover:shadow-md',
        isSelected && 'ring-2 ring-primary border-primary',
        className
      )}
      onClick={onClick}
      onDoubleClick={onDoubleClick}
    >
      {/* Preview/Icon area */}
      <div className="relative aspect-square bg-muted/30 flex items-center justify-center overflow-hidden">
        {isImage ? (
          // Render image preview (public shows image, private shows lock icon)
          <ImagePreview
            accessUrl={accessUrl}
            thumbnailUrl={thumbnailUrl}
            name={name}
            isPrivate={visibility === 'PRIVATE'}
          />
        ) : isVideo ? (
          // Render video preview with inline player support
          // Supports both PUBLIC (CDN) and PRIVATE (API route) videos
          <VideoPreview
            fileId={id}
            organizationId={organizationId}
            thumbnailUrl={thumbnailUrl}
            posterUrl={posterUrl}
            hlsManifestUrl={hlsManifestUrl}
            visibility={visibility}
            videoProcessingStatus={videoProcessingStatus}
            name={name}
            isPlaying={isVideoPlaying}
            onPlayClick={handlePlayVideo}
            onCloseClick={handleCloseVideo}
          />
        ) : (
          // File type icon for non-visual files
          <FileIcon extension={extension} category={category} size="lg" />
        )}

        {/* Visibility badge - hide when video is playing */}
        {!isVideoPlaying && (
          <Badge
            variant={visibility === 'PUBLIC' ? 'default' : 'secondary'}
            className={cn(
              'absolute top-2 left-2 text-[10px] px-1.5 py-0.5',
              visibility === 'PUBLIC'
                ? 'bg-green-500/90 hover:bg-green-500'
                : 'bg-muted/90'
            )}
          >
            {visibility === 'PUBLIC' ? (
              <Globe className="w-3 h-3 mr-1" />
            ) : (
              <Lock className="w-3 h-3 mr-1" />
            )}
            {visibility === 'PUBLIC' ? 'Public' : 'Private'}
          </Badge>
        )}

        {/* Context menu trigger - hide when video is playing */}
        {!isVideoPlaying && (
          <DropdownMenu modal={true}>
            <DropdownMenuTrigger asChild>
              <Button
                variant="ghost"
                size="icon"
                className={cn(
                  'absolute top-2 right-2 h-7 w-7',
                  'bg-background/80 backdrop-blur-sm',
                  'opacity-0 group-hover:opacity-100 transition-opacity',
                  'hover:bg-background'
                )}
                onClick={(e) => e.stopPropagation()}
              >
                <MoreHorizontal className="h-4 w-4" />
              </Button>
            </DropdownMenuTrigger>
          <DropdownMenuContent
            align="end"
            className="w-48"
            onClick={(e) => e.stopPropagation()}
          >
            <DropdownMenuItem
              onClick={(e) => {
                e.stopPropagation()
                onDownload?.()
              }}
            >
              <Download className="w-4 h-4 mr-2" />
              Download
            </DropdownMenuItem>
            <DropdownMenuItem
              onClick={(e) => {
                e.stopPropagation()
                if (shareableUrl) {
                  // For private files, build full URL with origin
                  const fullUrl = visibility === 'PRIVATE'
                    ? `${window.location.origin}${shareableUrl}`
                    : shareableUrl
                  // Show appropriate message based on visibility
                  const message = visibility === 'PRIVATE'
                    ? 'Link copied - accessible for 15 minutes after opening'
                    : 'Link copied to clipboard'
                  copyToClipboard(fullUrl, message)
                } else {
                  toast.error('No URL available')
                }
              }}
            >
              <Link2 className="w-4 h-4 mr-2" />
              Copy Link
              {visibility === 'PRIVATE' && <Lock className="w-3 h-3 ml-auto text-muted-foreground" />}
            </DropdownMenuItem>
            <DropdownMenuItem
              onClick={(e) => {
                e.stopPropagation()
                // Enter inline edit mode - same as double-click on file name
                setIsEditing(true)
              }}
            >
              <Pencil className="w-4 h-4 mr-2" />
              Rename
            </DropdownMenuItem>
            <DropdownMenuItem
              onClick={(e) => {
                e.stopPropagation()
                onMove?.()
              }}
            >
              <Move className="w-4 h-4 mr-2" />
              Move to...
            </DropdownMenuItem>
            <DropdownMenuSeparator />
            <DropdownMenuItem
              onClick={(e) => {
                e.stopPropagation()
                onToggleVisibility?.()
              }}
            >
              {visibility === 'PUBLIC' ? (
                <>
                  <Lock className="w-4 h-4 mr-2" />
                  Make Private
                </>
              ) : (
                <>
                  <Globe className="w-4 h-4 mr-2" />
                  Make Public
                </>
              )}
            </DropdownMenuItem>
            <DropdownMenuSeparator />
            <DropdownMenuItem
              onClick={(e) => {
                e.stopPropagation()
                onDelete?.()
              }}
              className="text-destructive focus:text-destructive"
            >
              <Trash2 className="w-4 h-4 mr-2" />
              Delete
            </DropdownMenuItem>
          </DropdownMenuContent>
        </DropdownMenu>
        )}
      </div>

      {/* File info with inline rename */}
      <div className="p-3 space-y-1">
        {isEditing ? (
          // Inline edit mode
          <div className="flex items-center gap-1">
            <input
              ref={inputRef}
              type="text"
              value={editName}
              onChange={(e) => setEditName(e.target.value)}
              onKeyDown={handleKeyDown}
              onBlur={handleSaveName}
              onClick={(e) => e.stopPropagation()}
              disabled={isRenaming}
              className={cn(
                'flex-1 min-w-0 text-sm font-medium bg-transparent',
                'border-b border-primary outline-none',
                'focus:border-primary',
                isRenaming && 'opacity-50'
              )}
            />
          </div>
        ) : (
          // Display mode - double-click to edit
          <p
            className={cn(
              'text-sm font-medium truncate',
              onRename && 'cursor-text hover:bg-muted/50 rounded px-1 -mx-1 transition-colors'
            )}
            title={`${name} (double-click to rename)`}
            onDoubleClick={handleNameDoubleClick}
          >
            {name}
          </p>
        )}
        <p className="text-xs text-muted-foreground">
          {formatFileSize(size)} • {extension.toUpperCase()}
        </p>
      </div>
    </div>
  )
}

// ============================================================================
// FILE GRID COMPONENT
// ============================================================================

interface FileGridProps {
  children: React.ReactNode
  className?: string
}

/**
 * Grid layout for file cards
 * Responsive grid that adapts to screen size
 */
export function FileGrid({ children, className }: FileGridProps) {
  return (
    <div
      className={cn(
        'grid gap-4',
        'grid-cols-2 sm:grid-cols-3 md:grid-cols-4 lg:grid-cols-5 xl:grid-cols-6',
        className
      )}
    >
      {children}
    </div>
  )
}

// ============================================================================
// FILE LIST ITEM (Alternative view)
// ============================================================================

interface FileListItemProps extends Omit<FileCardProps, 'className'> {
  /** Created date */
  createdAt?: Date
  /** Additional className */
  className?: string
}

/**
 * File displayed as a list item instead of card
 * Used for list view in file manager
 * Shows small thumbnail for images/videos, icon for others
 *
 * Supports inline rename on double-click (same as FileCard)
 */
export function FileListItem({
  id,
  name,
  extension,
  category,
  size,
  thumbnailUrl,
  accessUrl,
  publicUrl,
  visibility,
  createdAt,
  isSelected,
  onClick,
  onDoubleClick,
  onRename,
  isRenaming,
  onDelete,
  onMove,
  onDownload,
  onToggleVisibility,
  className,
}: FileListItemProps) {
  // State for inline name editing
  const [isEditing, setIsEditing] = useState(false)
  const [editName, setEditName] = useState(name)
  const inputRef = useRef<HTMLInputElement>(null)

  const isImage = category === 'IMAGE'
  const isVideo = category === 'VIDEO'
  const canShowPreview = isVisualFile(category)

  // Both PUBLIC and PRIVATE files can have shareable links
  // PUBLIC: Direct CDN URL (anyone can access)
  // PRIVATE: Authenticated API route (only logged-in org members can access)
  const shareableUrl = visibility === 'PUBLIC' ? publicUrl : `/api/storage/${id}`

  // For list view, use accessUrl for both PUBLIC and PRIVATE files
  // Private files use API route (/api/storage/[fileId]) which redirects to presigned R2 URL
  const imagePreviewUrl = accessUrl || thumbnailUrl
  const isPrivate = visibility === 'PRIVATE'

  // Focus input when entering edit mode
  useEffect(() => {
    if (isEditing && inputRef.current) {
      inputRef.current.focus()
      inputRef.current.select()
    }
  }, [isEditing])

  // Reset edit name when name prop changes (e.g., after successful rename)
  useEffect(() => {
    setEditName(name)
  }, [name])

  /**
   * Enter edit mode on double-click
   */
  const handleNameDoubleClick = useCallback((e: React.MouseEvent) => {
    e.stopPropagation()
    if (!onRename) return
    setIsEditing(true)
  }, [onRename])

  /**
   * Save the new name
   */
  const handleSaveName = useCallback(() => {
    const trimmedName = editName.trim()
    if (trimmedName && trimmedName !== name) {
      onRename?.(trimmedName)
    }
    setIsEditing(false)
  }, [editName, name, onRename])

  /**
   * Cancel editing and reset name
   */
  const handleCancelEdit = useCallback(() => {
    setEditName(name)
    setIsEditing(false)
  }, [name])

  /**
   * Handle keyboard events in edit mode
   */
  const handleKeyDown = useCallback((e: React.KeyboardEvent) => {
    if (e.key === 'Enter') {
      e.preventDefault()
      handleSaveName()
    } else if (e.key === 'Escape') {
      e.preventDefault()
      handleCancelEdit()
    }
  }, [handleSaveName, handleCancelEdit])

  return (
    <div
      className={cn(
        'group flex items-center gap-4 p-3 rounded-lg cursor-pointer transition-all',
        'hover:bg-muted/50',
        isSelected && 'bg-muted ring-1 ring-primary/50',
        className
      )}
      onClick={onClick}
      onDoubleClick={onDoubleClick}
    >
      {/* Preview/Icon - Small thumbnail for images/videos, or file icon */}
      <div className="w-10 h-10 flex-shrink-0 rounded-md overflow-hidden bg-muted/30 flex items-center justify-center relative">
        {canShowPreview && imagePreviewUrl ? (
          <>
            {/**
             * Private files: Use regular <img> because accessUrl is an API route
             * that redirects to a presigned R2 URL. next/image can't follow redirects.
             * Public files: Use next/image for optimized CDN loading.
             */}
            {isPrivate ? (
              <img
                src={imagePreviewUrl}
                alt={name}
                className="object-cover w-full h-full"
              />
            ) : (
              <Image
                src={imagePreviewUrl}
                alt={name}
                width={40}
                height={40}
                className="object-cover w-full h-full"
              />
            )}
            {/* Small play indicator for videos */}
            {isVideo && (
              <div className="absolute inset-0 flex items-center justify-center bg-black/30">
                <Play className="w-4 h-4 text-white fill-white" />
              </div>
            )}
          </>
        ) : (
          <FileIcon extension={extension} category={category} size="sm" />
        )}
      </div>

      {/* File info with inline rename */}
      <div className="flex-1 min-w-0">
        {isEditing ? (
          // Inline edit mode
          <input
            ref={inputRef}
            type="text"
            value={editName}
            onChange={(e) => setEditName(e.target.value)}
            onKeyDown={handleKeyDown}
            onBlur={handleSaveName}
            onClick={(e) => e.stopPropagation()}
            disabled={isRenaming}
            className={cn(
              'w-full text-sm font-medium bg-transparent',
              'border-b border-primary outline-none',
              'focus:border-primary',
              isRenaming && 'opacity-50'
            )}
          />
        ) : (
          // Display mode - double-click to edit
          <p
            className={cn(
              'text-sm font-medium truncate',
              onRename && 'cursor-text hover:bg-muted/50 rounded px-1 -mx-1 transition-colors'
            )}
            title={`${name} (double-click to rename)`}
            onDoubleClick={handleNameDoubleClick}
          >
            {name}
          </p>
        )}
        <p className="text-xs text-muted-foreground">
          {formatFileSize(size)}
          {createdAt && ` • ${createdAt.toLocaleDateString()}`}
        </p>
      </div>

      {/* Visibility badge */}
      <Badge
        variant={visibility === 'PUBLIC' ? 'default' : 'secondary'}
        className={cn(
          'text-[10px] px-1.5 py-0.5',
          visibility === 'PUBLIC'
            ? 'bg-green-500/90 hover:bg-green-500'
            : 'bg-muted'
        )}
      >
        {visibility === 'PUBLIC' ? 'Public' : 'Private'}
      </Badge>

      {/* Actions */}
      <DropdownMenu modal={true}>
        <DropdownMenuTrigger asChild>
          <Button
            variant="ghost"
            size="icon"
            className="h-8 w-8 opacity-0 group-hover:opacity-100"
            onClick={(e) => e.stopPropagation()}
          >
            <MoreHorizontal className="h-4 w-4" />
          </Button>
        </DropdownMenuTrigger>
        <DropdownMenuContent
          align="end"
          className="w-48"
          onClick={(e) => e.stopPropagation()}
        >
          <DropdownMenuItem
            onClick={(e) => {
              e.stopPropagation()
              onDownload?.()
            }}
          >
            <Download className="w-4 h-4 mr-2" />
            Download
          </DropdownMenuItem>
          <DropdownMenuItem
            onClick={(e) => {
              e.stopPropagation()
              if (shareableUrl) {
                // For private files, build full URL with origin
                const fullUrl = visibility === 'PRIVATE'
                  ? `${window.location.origin}${shareableUrl}`
                  : shareableUrl
                // Show appropriate message based on visibility
                const message = visibility === 'PRIVATE'
                  ? 'Link copied - accessible for 15 minutes after opening'
                  : 'Link copied to clipboard'
                copyToClipboard(fullUrl, message)
              } else {
                toast.error('No URL available')
              }
            }}
          >
            <Link2 className="w-4 h-4 mr-2" />
            Copy Link
            {visibility === 'PRIVATE' && <Lock className="w-3 h-3 ml-auto text-muted-foreground" />}
          </DropdownMenuItem>
          <DropdownMenuItem
            onClick={(e) => {
              e.stopPropagation()
              // Enter inline edit mode - same as double-click on file name
              setIsEditing(true)
            }}
          >
            <Pencil className="w-4 h-4 mr-2" />
            Rename
          </DropdownMenuItem>
          <DropdownMenuItem
            onClick={(e) => {
              e.stopPropagation()
              onMove?.()
            }}
          >
            <Move className="w-4 h-4 mr-2" />
            Move to...
          </DropdownMenuItem>
          <DropdownMenuSeparator />
          <DropdownMenuItem
            onClick={(e) => {
              e.stopPropagation()
              onToggleVisibility?.()
            }}
          >
            {visibility === 'PUBLIC' ? (
              <>
                <Lock className="w-4 h-4 mr-2" />
                Make Private
              </>
            ) : (
              <>
                <Globe className="w-4 h-4 mr-2" />
                Make Public
              </>
            )}
          </DropdownMenuItem>
          <DropdownMenuSeparator />
          <DropdownMenuItem
            onClick={(e) => {
              e.stopPropagation()
              onDelete?.()
            }}
            className="text-destructive focus:text-destructive"
          >
            <Trash2 className="w-4 h-4 mr-2" />
            Delete
          </DropdownMenuItem>
        </DropdownMenuContent>
      </DropdownMenu>
    </div>
  )
}

// ============================================================================
// FILE CARD SKELETON
// ============================================================================

interface FileCardSkeletonProps {
  className?: string
}

/**
 * Loading skeleton that matches FileCard layout EXACTLY.
 * Uses identical wrapper classes and dimensions for seamless transition.
 */
export function FileCardSkeleton({ className }: FileCardSkeletonProps) {
  return (
    <div
      className={cn(
        // Exact same wrapper classes as FileCard
        'group relative flex flex-col rounded-xl overflow-hidden',
        'border border-border/50 bg-card',
        className
      )}
    >
      {/* Preview area - exact same classes as FileCard */}
      <div className="relative aspect-square bg-muted/30 flex items-center justify-center overflow-hidden">
        {/* Subtle centered icon placeholder */}
        <div className="w-10 h-10 rounded-lg bg-muted/50 animate-pulse" />
      </div>

      {/* File info - exact same classes as FileCard */}
      <div className="p-3 space-y-1">
        {/* Filename placeholder - matches text-sm font-medium */}
        <div className="h-[14px] w-4/5 rounded bg-muted animate-pulse" />
        {/* Size placeholder - matches text-xs */}
        <div className="h-[12px] w-1/2 rounded bg-muted/60 animate-pulse" />
      </div>
    </div>
  )
}

// ============================================================================
// FILE LIST ITEM SKELETON
// ============================================================================

interface FileListItemSkeletonProps {
  className?: string
}

/**
 * Loading skeleton that matches FileListItem layout EXACTLY.
 * Uses identical wrapper classes and dimensions for seamless transition.
 */
export function FileListItemSkeleton({ className }: FileListItemSkeletonProps) {
  return (
    <div
      className={cn(
        // Exact same wrapper classes as FileListItem
        'group flex items-center gap-4 p-3 rounded-lg',
        className
      )}
    >
      {/* Thumbnail - exact same size as FileListItem */}
      <div className="w-10 h-10 flex-shrink-0 rounded-md bg-muted/30 animate-pulse" />

      {/* File info - exact same wrapper as FileListItem */}
      <div className="flex-1 min-w-0 space-y-1">
        {/* Filename - matches text-sm font-medium */}
        <div className="h-[14px] w-3/5 rounded bg-muted animate-pulse" />
        {/* Size - matches text-xs */}
        <div className="h-[12px] w-1/4 rounded bg-muted/60 animate-pulse" />
      </div>

      {/* Badge placeholder */}
      <div className="h-5 w-14 rounded-full bg-muted/40 animate-pulse" />
    </div>
  )
}
